CREATE TABLE IF NOT EXISTS users(id SERIAL PRIMARY KEY, email TEXT UNIQUE NOT NULL, password_hash TEXT NOT NULL, created_at TIMESTAMPTZ DEFAULT now());
CREATE TABLE IF NOT EXISTS categories(id SERIAL PRIMARY KEY, user_id INT NOT NULL REFERENCES users ON DELETE CASCADE, name TEXT NOT NULL, color TEXT DEFAULT '#64748b');
CREATE TABLE IF NOT EXISTS transactions(
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(), user_id INT NOT NULL REFERENCES users ON DELETE CASCADE,
  type TEXT NOT NULL CHECK (type IN ('income','expense')), amount NUMERIC(12,2) NOT NULL CHECK (amount>0),
  description TEXT DEFAULT '', category_id INT REFERENCES categories ON DELETE SET NULL, date DATE NOT NULL, created_at TIMESTAMPTZ DEFAULT now());
CREATE INDEX IF NOT EXISTS idx_tx_user_date ON transactions(user_id,date);
CREATE TABLE IF NOT EXISTS goals(id SERIAL PRIMARY KEY, user_id INT NOT NULL REFERENCES users ON DELETE CASCADE, name TEXT NOT NULL, target NUMERIC(12,2) NOT NULL, saved NUMERIC(12,2) DEFAULT 0, created_at TIMESTAMPTZ DEFAULT now());
